"""Strategy scaffolder — generate a new strategy module from a name.

Powers `stinger-fx strategy scaffold NAME`. Produces a self-contained file
that already imports the right base classes, declares a typed Params model,
declares a subscription, and overrides the most common lifecycle hooks with
TODO comments — so the author starts editing instead of starting from a
blank file.

The scaffolder also prints the YAML snippet to paste into
`config/strategies.yaml` so the new strategy can be activated immediately.
"""

from __future__ import annotations

import re
from pathlib import Path

VALID_NAME = re.compile(r"^[a-z][a-z0-9_]*$")


class ScaffoldError(ValueError):
    """Raised when the scaffold input is invalid or the output already exists."""


def snake_to_pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


_TEMPLATE = '''"""{class_name} — autogenerated strategy stub.

Generated by `stinger-fx strategy scaffold {name}`. Edit freely.
"""

from __future__ import annotations

from pydantic import Field

from stinger_fx.domain import Bar, Subscription, Timeframe
from stinger_fx.strategies.base import BaseStrategy
from stinger_fx.strategies.context import StrategyContext
from stinger_fx.strategies.indicators import sma
from stinger_fx.strategies.parameters import StrategyParams


class {class_name}Params(StrategyParams):
    """Typed parameters for {class_name}.

    Every field becomes a knob you can change in `config/strategies.yaml`.
    """

    symbol: str = "EURUSD"
    timeframe: Timeframe = Timeframe.M15
    fast: int = Field(10, ge=2, le=200)
    slow: int = Field(30, ge=5, le=500)
    volume: float = Field(0.01, gt=0)


class {class_name}(BaseStrategy):
    """TODO: describe what this strategy does."""

    name = "{name}"
    Params = {class_name}Params

    @classmethod
    def subscriptions(cls, params: StrategyParams) -> list[Subscription]:
        assert isinstance(params, {class_name}Params)
        return [Subscription(symbol=params.symbol, timeframe=params.timeframe)]

    # ----------------------------------------------------------------------
    # Lifecycle hooks — override the ones you care about. Defaults are no-ops.
    # ----------------------------------------------------------------------

    async def on_start(self, ctx: StrategyContext) -> None:
        ctx.logger.info("{name}_started", params=ctx.params.model_dump())

    async def on_bar(self, ctx: StrategyContext, bar: Bar) -> None:
        params = ctx.params
        assert isinstance(params, {class_name}Params)

        closes = ctx.history.closes()
        if len(closes) < params.slow + 2:
            return  # not enough history yet

        fast_ma = sma(closes, params.fast)
        slow_ma = sma(closes, params.slow)
        if fast_ma is None or slow_ma is None:
            return

        # TODO: replace this placeholder logic with your real entry/exit rules.
        ctx.logger.debug(
            "{name}_bar",
            symbol=bar.symbol,
            close=bar.close,
            fast=fast_ma,
            slow=slow_ma,
        )

    async def on_stop(self, ctx: StrategyContext) -> None:
        ctx.logger.info("{name}_stopped")
'''


def scaffold(
    name: str,
    target_dir: Path,
    *,
    force: bool = False,
) -> Path:
    """Write a new strategy module under `target_dir`.

    Returns the path to the generated file.
    Raises ScaffoldError on invalid name or existing file (unless `force`).
    """
    if not VALID_NAME.match(name):
        raise ScaffoldError(
            f"strategy name {name!r} must be snake_case "
            "(start with a-z, contain only a-z 0-9 _)"
        )
    target_dir.mkdir(parents=True, exist_ok=True)
    # Ensure the directory is a package
    init = target_dir / "__init__.py"
    if not init.exists():
        init.write_text("")
    out = target_dir / f"{name}.py"
    if out.exists() and not force:
        raise ScaffoldError(f"{out} already exists (pass --force to overwrite)")

    class_name = snake_to_pascal(name)
    out.write_text(_TEMPLATE.format(name=name, class_name=class_name))
    return out


def yaml_snippet(name: str, module_path: str) -> str:
    """Return the strategies.yaml block the user should paste."""
    return (
        f"  - id: {name}\n"
        f"    class_path: {module_path}:{snake_to_pascal(name)}\n"
        f"    enabled: true\n"
        f"    params:\n"
        f"      symbol: EURUSD\n"
        f"      timeframe: M15\n"
        f"      fast: 10\n"
        f"      slow: 30\n"
        f"      volume: 0.01\n"
    )


def derive_module_path(file_path: Path, repo_root: Path) -> str:
    """Convert `repo_root/src/stinger_fx/strategies/user/foo.py` to
    `stinger_fx.strategies.user.foo`. Best effort — if the file is outside
    a known src layout, returns just the filename stem.
    """
    try:
        rel = file_path.resolve().relative_to(repo_root.resolve())
    except ValueError:
        return file_path.stem
    parts = rel.parts
    if parts and parts[0] == "src":
        parts = parts[1:]
    if not parts:
        return file_path.stem
    *dirs, last = parts
    return ".".join([*dirs, last[: -len(".py")] if last.endswith(".py") else last])
