[mypy]
python_version = 3.12
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
ignore_missing_imports = True
plugins = pydantic.mypy

[mypy-stinger_fx.core.*]
disallow_untyped_defs = True
strict_equality = True

[mypy-stinger_fx.domain.*]
disallow_untyped_defs = True
strict_equality = True

[mypy-stinger_fx.config.*]
disallow_untyped_defs = True

[mypy-MetaTrader5]
ignore_missing_imports = True
